steps:
    - id: 'Copy Coverity to build'
      name: "gcr.io/cloud-builders/gsutil"
      args: ['cp', 'gs://coverity-latest/coverity-full/*', '.']
    - id: 'Run Coverity scanning script'
      name: 'debian'
      args: ['bash', './coverity-scanning.sh']
      env:
        - '_COV_BUILD=$_COV_BUILD'
        - '_COV_ANALYZE=$_COV_ANALYZE'
        - '_COV_USR=$_COV_USR'
        - '_COV_PASS=$_COV_PASS'
        - '_COV_STREAM=$_COV_STREAM'
        - '_COV_CONFIG=$_COV_CONFIG'
timeout: 36000s
