steps:
    - id: 'copy coverity'
      name: "gcr.io/cloud-builders/gsutil"
      args: ['cp', 'gs://coverity-latest/coverity-full/*', '.']
    - id: 'Unzip Coverity'
      name: 'debian'
      args: ['bash', './coverity-scanning.sh']
timeout: 3600s