steps:
    - id: 'Copy Coverity to build'
      name: "gcr.io/cloud-builders/gsutil"
      args: ['cp', 'gs://coverity-latest/coverity-full/*', '.']
    - id: 'Run Coverity scanning script'
      name: 'debian'
      args: ['bash', './coverity-scanning.sh']
timeout: 36000s
options:
  machineType: 'N1_HIGHCPU_8'